=== pypi-data/pypi-mirror-84/packages/inary/inary-1.4.2-1.tar.gz/inary-1.4.2-1/inary-spec.dtd
<!-- Document Type Declaration file for INARY pspec.xml files -->
<!-- https://gitlab.com/sulinos/devel/inary -->

<!ELEMENT INARY (Source,Package+,History)>

<!-- Source Section -->

<!ELEMENT Source (
	#PCDATA |
	Name |
	Homepage |
	Icon |
	Rfp |
	Packager |
	ExcludeArch |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	Archive |
	AdditionalFiles |
	Patches |
	BuildDependencies
)*>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT Rfp (#PCDATA)>

<!ELEMENT Packager (Name, Email)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT ExcludeArch (#PCDATA)>

<!ELEMENT License (#PCDATA)>

<!ELEMENT IsA (#PCDATA)>

<!ELEMENT PartOf (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>
<!ATTLIST Summary xml:lang CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description xml:lang CDATA #IMPLIED>

<!ELEMENT Archive (#PCDATA)>
<!ATTLIST Archive sha1sum CDATA #REQUIRED>
<!-- NOTE: we can limit possible types here to the ones that inary know -->
<!ATTLIST Archive type CDATA #REQUIRED>
<!ATTLIST Archive target CDATA #IMPLIED>

<!ELEMENT BuildFlags (Flag*)>

<!ELEMENT Flag (#PCDATA)>

<!ELEMENT BuildType (#PCDATA)>

<!ELEMENT BuildDependencies (Dependency*)>

<!ELEMENT Dependency (#PCDATA)>
<!ATTLIST Dependency versionFrom CDATA #IMPLIED>
<!ATTLIST Dependency versionTo CDATA #IMPLIED>
<!ATTLIST Dependency version CDATA #IMPLIED>
<!ATTLIST Dependency releaseFrom CDATA #IMPLIED>
<!ATTLIST Dependency releaseTo CDATA #IMPLIED>
<!ATTLIST Dependency release CDATA #IMPLIED>
<!ATTLIST Dependency type CDATA #IMPLIED>

<!ELEMENT Patches (Patch*)>

<!ELEMENT Patch (#PCDATA)>
<!ATTLIST Patch compressionType CDATA #IMPLIED>
<!ATTLIST Patch level CDATA #IMPLIED>
<!ATTLIST Patch target CDATA #IMPLIED>
<!ATTLIST Patch reverse CDATA #IMPLIED>


<!-- Package Section -->

<!ELEMENT Package (
	#PCDATA |
	Name |
	License |
	Icon |
	Rfp |
	IsA |
	PartOf |
	Summary |
	Description |
	BuildFlags |
	BuildType |
	BuildDependencies |
	RuntimeDependencies |
	Files |
	Conflicts |
	Replaces |
	AdditionalFiles |
	Provides
)*>


<!ELEMENT Provides (CMAKE)>
<!ELEMENT CMAKE (#PCDATA)>
<!ELEMENT Provides (PkgConfig)>
<!ELEMENT PkgConfig (#PCDATA)>
<!ELEMENT Provides (Command)>
<!ELEMENT Command (#PCDATA)>
<!ELEMENT Provides (SharedObject)>
<!ELEMENT SharedObject (#PCDATA)>
<!ELEMENT Provides (Service)>
<!ELEMENT Service (#PCDATA)>
<!ATTLIST Service runlevel CDATA #IMPLIED>

<!ELEMENT Conflicts (Package)+>
<!-- we have a problem here, this Package tag only contains a package name
while dtd treats this as another Package section, who said dtd doesnt
suck anyway -->
<!ATTLIST Package versionFrom CDATA #IMPLIED>
<!ATTLIST Package versionTo CDATA #IMPLIED>
<!ATTLIST Package version CDATA #IMPLIED>
<!ATTLIST Package releaseFrom CDATA #IMPLIED>
<!ATTLIST Package releaseTo CDATA #IMPLIED>
<!ATTLIST Package release CDATA #IMPLIED>

<!ELEMENT Replaces (Package)+>

<!ELEMENT AdditionalFiles (AdditionalFile+)>
<!ELEMENT AdditionalFile (#PCDATA)>
<!ATTLIST AdditionalFile target CDATA #REQUIRED>
<!ATTLIST AdditionalFile permission CDATA #IMPLIED>
<!ATTLIST AdditionalFile owner CDATA #IMPLIED>

<!ELEMENT RuntimeDependencies (Dependency*)>

<!ELEMENT Files (Path)+>

<!ELEMENT Path (#PCDATA)>
<!-- NOTE: is this list correct? -->
<!ATTLIST Path fileType
	(executable|library|data|config|doc|man|info|localedata|header)
	#REQUIRED>
<!ATTLIST Path permanent (false|true) #IMPLIED>
<!ATTLIST Path replace (false|true) #IMPLIED>


<!-- History Section -->

<!ELEMENT History (Update+)>

<!ELEMENT Update (#PCDATA | Date | Version | Comment | Type | Requires | Name | Email)*>
<!ATTLIST Update release CDATA #REQUIRED>
<!ATTLIST Update type (critical|security) #IMPLIED>

<!ELEMENT Date (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type package CDATA #IMPLIED>

<!ELEMENT Requires (Action+)>

<!ELEMENT Action (#PCDATA)>
<!ATTLIST Action package CDATA #IMPLIED>
<!ATTLIST Action target CDATA #IMPLIED>

=== pypi-data/pypi-mirror-84/packages/inary/inary-1.4.2-1.tar.gz/inary-1.4.2-1/tests/buildTest/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE INARY SYSTEM "https://raw.githubusercontent.com/Zaryob/inary/master/inary-spec.dtd">
<INARY>
    <Source>
        <Name>unibuild</Name>
        <Homepage>https://gitlab.com/sulinos/devel/inary</Homepage>
        <Packager>
            <Name>Ali Rıza KESKİN</Name>
            <Email>parduscix@yandex.ru</Email>
        </Packager>
        <License>GPLv2</License>
        <IsA>app:console</IsA>
        <PartOf>system.base</PartOf>
        <Summary>unibuild package build test</Summary>
        <Description>Pakcage build test for inary.</Description>
        <!--Archive sha1sum="master" >https://gitlab.com/sulinos/devel/unibuild.git</Archive-->
        <Archive sha1sum="e5f5a0721c01549bdaf7c862021b80e8b037c13a">https://gitlab.com/sulinos/devel/unibuild/-/archive/master/unibuild-master.tar.gz</Archive>
    </Source>

    <Package>
        <IsA>postOps</IsA>
        <Name>unibuild</Name>
        <Files>
            <Path fileType="executable">/usr/bin</Path>
            <Path fileType="library">/usr/lib</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2020-01-28</Date>
            <Version>31.42.543a</Version>
            <Comment>First release</Comment>
            <Name>Ali Rıza KESKİN</Name>
            <Email>parduscix@yandex.ru</Email>
        </Update>
    </History>
</INARY>
